### ISSUE TITLE
How can I properly use this?

### ISSUE THREAD

**Issue by ucanzeee** [doomsower/react-native-startup-time#12]
I am using vscode. I don't use android studio at all, but the instructions are strictly for android studio it seems. I didn't see anyone who use android studio for that anyway. You don't even use anything related with android studio much in react. You don't need it. This is javascript anyway, android studio has nothing to do with this. Even in youtube tutorials none uses android studio for that.

Anyway here s what I did and what didn't work.

import { StartupTime } from 'react-native-startup-time';
...
 
<StartupTime
    ready={true /* optional, defaults to true */}
    style={styles.startupTime /* optional*/}
/>
a=StartupTime

console.log(a)
**************************************
import { getTimeSinceStartup } from 'react-native-startup-time';
 
// when you app is ready:
getTimeSinceStartup().then((time) => {
  console.log(`Time since startup: ${time} ms`);
});
a=getTimeSinceStartup()

console.log(a)

**********************

Both returns null. I tried various things, its just a small thing I didn't expect it give so much errors at start. That's why I think a little more documentation would be good. I even copy pasted that and it still doesn't work.

**Comment by doomsower** [comment]
> I am using vscode. I don't use android studio at all, but the instructions are strictly for android studio it seems. I didn't see anyone who use android studio for that anyway. You don't even use anything related with android studio much in react. You don't need it. This is javascript anyway, android studio has nothing to do with this.

This has nothing to do with Android studio, it's not even mentioned in readme at all. And if you use RN beyond basic things (and performance optimization is one of such use cases), then you have to understand how native parts of RN work, and you will have to mess with native parts occasionally.

>  Even in youtube tutorials none uses android studio for that.

This is a weighty argument, but also not true. It depends on what are you looking for. Videos on performance optimizations and native parts do feature android studio.

I don't understand what are you trying to achieve with this code:
```js
// ...
a=StartupTime
console.log(a)
// ...
a=getTimeSinceStartup()
console.log(a)
```
Are you checking that module has been installed correctly? It's not supposed to return nulls anyway, event when installed incorrectly. They will throw when it's not installed correctly, because `RNStartupTime` will be undefined [here](https://github.com/doomsower/react-native-startup-time/blob/master/index.js)

Which version of RN are you using? Older versions will required manual linking, and even older might not be compatible with this module at all. Also, are you using Expo? This module doesn't work with Expo.

**Comment by ucanzeee** [comment]
> are you using Expo? This module doesn't work with Expo.

Yes. This must be it then. Sorry for troubling you. Because in expo you don't have any android and gradle files. So now I am using react native CLI actually. 

I have those files, but as soon as I add import in app.js, it shows the starting screen but meanwhile it gives an error. Can I show startup time in the actual phone or in terminal, outputs?

**Comment by doomsower** [comment]
Expo doesn't support arbitrary native modules like this one [(source)](https://docs.expo.io/expokit/eject/#you-might-want-to-eject-if). Maybe they have their own tools for profiling...

**Comment by ucanzeee** [comment]
I literally have react native CLI version now, it even acknowledges import too. I wanna use getTimeSinceStartup() method but how? Whereever I put getTimeSinceStartup its either invisible or if put in wrong place, "Text strings must be rendered within a <Text> component" it says.
